[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = { version = "0.17", features = ["rayon"] }
rand = "0.8"
rayon = "1.8"
vek = "0.16"

[profile.release]
debug = true