[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
indicatif = { version = "0.17", features = ["rayon"] }
noise = { version = "0.8", features = ["images"] }
rand = { version="0.8", features = ["small_rng"] }
rayon = "1"
vek = "0.16"